function SRIMRangeDist()
%% SRIM Range Distribution
%  A GUI for plotting multiple profiles of SRIM Range Distribution of Ions.
%
%  SRIM is a software that does Monte Carlo simulation of ion implantations. It
%  can estimate the distribution of ions and target damages after an
%  implantation. SRIMRangeDist helps SRIM users to plot the ion distribution
%  data from a SRIM output with relative ease. In some occassions, SRIM users
%  need to calculate the distribution statistics of a series of several ion
%  implantations and do a trial-and-error work to get the optimal implantation
%  parameters. Performing this kind of task manually in a data processing
%  software can be a bit mundane. SRIMRangeDist allows users to plot multiple
%  implantation profiles on the same graph, and it computes the total
%  distribution and the 95% confidence interval of the distribution for a quick
%  reviewing of many implantation scenarios.
%
% Main features:
%  - Plot up to seven SRIM data from multiple implantation profiles.
%  - Compute the mean and range of the 95% CI of the total ion distribution.
%
% How to use:
%  1. Put the RANGE.txt file from a SRIM output into a folder with an integer
%     name, and then put this folder into another folder so that the directory
%     looks like, for example: "data/123/RANGE.txt". Tips: choose the integer to
%     be the implantation energy used.
%  2. Specify the "data" folder, target's mass density, and target's molar mass
%     in the user interface.
%  3. Also specify a few pairs of subfolder number and the corresponding
%     implantation fluence in the input table.
%  4. The x-axis limit can be optionally set.
%  5. Push the PLOT button.
%
% Tested on:
%  - MATLAB R2015b
%
% Copyright: Herianto Lim
% http://heriantolim.com/
% First created: 31/01/2016
% Last modified: 01/02/2015

%% Parameters
% Layout
FIGURE_WIDTH=1130;% pixels
FIGURE_HEIGHT=635;% pixels
SIDEBAR_WIDTH=282;% pixels
UI_LABEL_POSITION={ ...
	[30,580,SIDEBAR_WIDTH,25], ...
	[30,510,SIDEBAR_WIDTH,25], ...
	[30+SIDEBAR_WIDTH-60,480,60,25], ...
	[30,440,SIDEBAR_WIDTH,25], ...
	[30+SIDEBAR_WIDTH-60,410,60,25], ...
	[30,370,SIDEBAR_WIDTH,25], ...
	[30,150,SIDEBAR_WIDTH,25]};% pixels
x=SIDEBAR_WIDTH/2-10;
INPUT_TEXT_POSITION={ ...
	[30,550,SIDEBAR_WIDTH-60,25], ...
	[30,480,SIDEBAR_WIDTH-60,25], ...
	[30,410,SIDEBAR_WIDTH-60,25], ...
	[30,120,x,25], ...
	[30+x+20,120,x,25]};% pixels
INPUT_TABLE_POSITION=[30,190,SIDEBAR_WIDTH,176];% pixels
PUSH_BUTTON_POSITION={ ...
	[30+SIDEBAR_WIDTH-50,550,50,25], ...
	[30,30,SIDEBAR_WIDTH,60]};% pixels
AXES_POSITION=[SIDEBAR_WIDTH+120,80,698,525];% pixels

% Colors
FIGURE_BACKGROUND_COLOR='w';
INPUT_TEXT_BACKGROUND_COLOR=[.95,.95,.95];
PUSH_BUTTON_BACKGROUND_COLOR=[.9,.9,.9];
AXES_BACKGROUND_COLOR='w';
AXES_COLOR='k';
AXES_LABEL_COLOR='k';

% Fonts
FONT_STYLE='Times New Roman';
UI_LABEL_FONT_SIZE=12;% points
INPUT_TEXT_FONT_SIZE=12;% points
INPUT_TABLE_FONT_SIZE=11;% points
PUSH_BUTTON_FONT_SIZE=[12,14];% points
AXES_FONT_SIZE=12;% points
AXES_LABEL_FONT_SIZE=14;% points

% Texts
FIGURE_NAME='SRIM Range Distribution';
UI_LABEL_STRING={ ...
	'Data Folder:', ...
	'Target''s Mass Density:', ...
	'g/cm^3', ...
	'Target''s Molar Mass:', ...
	'g/mol', ...
	'Implantation Parameters:', ...
	'X-Axis Limit:'};
UI_LABEL_HORIZONTAL_ALIGNMENT={ ...
	'left', ...
	'left', ...
	'right', ...
	'left', ...
	'right', ...
	'left', ...
	'left'};
INPUT_TEXT_HORIZONTAL_ALIGNMENT={ ...
	'left', ...
	'right', ...
	'right', ...
	'right', ...
	'left'};
INPUT_TABLE_COLUMN_NAME={ ...
	'Subfolder #', ...
	'Fluence (cm^{-2})'};
PUSH_BUTTON_STRING={ ...
	'SELECT', ...
	'PLOT'};
X_LABEL_STRING='Depth (nm)';
Y_LABEL_STRING='Concentration (%)';

% Line widths
AXES_LINE_WIDTH=1;

%% Figure
set(0,'DefaultAxesFontName',FONT_STYLE);
set(0,'DefaultTextFontName',FONT_STYLE);
delete(findobj('Tag','SRIMRangeDist'));% kill previous runs
FigureHandle=figure( ...
	'Units','pixels', ...
	'Position',[0,0,FIGURE_WIDTH,FIGURE_HEIGHT], ...
	'Visible','off', ...
	'Color',FIGURE_BACKGROUND_COLOR, ...
	'InvertHardCopy','off', ...
	'Name',FIGURE_NAME, ...
	'NumberTitle','off', ...
	'Resize','off', ...
	'Tag','SRIMRangeDist');

%% UI Controls
% Labels
UILabelHandle=zeros(1,7);
for i=1:7
	UILabelHandle(i)=uicontrol( ...
		'Parent',FigureHandle, ...
		'Units','pixels', ...
		'Position',UI_LABEL_POSITION{i}, ...
		'Style','text', ...
		'String',UI_LABEL_STRING{i}, ...
		'BackgroundColor',FIGURE_BACKGROUND_COLOR, ...
		'FontSize',UI_LABEL_FONT_SIZE, ...
		'HorizontalAlignment',UI_LABEL_HORIZONTAL_ALIGNMENT{i});
end

% Input texts
InputTextHandle=zeros(1,5);
for i=1:5
	InputTextHandle(i)=uicontrol( ...
		'Parent',FigureHandle, ...
		'Units','pixels', ...
		'Position',INPUT_TEXT_POSITION{i}, ...
		'Style','edit', ...
		'BackgroundColor',INPUT_TEXT_BACKGROUND_COLOR, ...
		'FontSize',INPUT_TEXT_FONT_SIZE, ...
		'HorizontalAlignment',INPUT_TEXT_HORIZONTAL_ALIGNMENT{i}, ...
		'Tag',sprintf('InputText%d',i));
end
set(InputTextHandle(1), ...
	'TooltipString',sprintf(['Select the data folder.\nThe folder must ', ...
		'have sub-folders with integer names,\nand each sub-folder must ', ...
		'contain a SRIM file: ''RANGE.txt''.']));
set(InputTextHandle(2), ...
	'Callback',@SRIMRangeDist.Callback.InputText2, ...
	'TooltipString',['Input the mass density of the target medium here ', ...
		'with a positive real number.']);
set(InputTextHandle(3), ...
	'Callback',@SRIMRangeDist.Callback.InputText3, ...
	'TooltipString',['Input the molar mass of the target medium here with ', ...
	'a positive real number.']);
set(InputTextHandle(4), ...
	'Callback',@SRIMRangeDist.Callback.InputText4, ...
	'TooltipString','Input the lower limit of the x-axis here.');
set(InputTextHandle(5), ...
	'Callback',@SRIMRangeDist.Callback.InputText5, ...
	'TooltipString','Input the upper limit of the x-axis here.');

% Input table
x=(SIDEBAR_WIDTH-32)/2;
uitable( ...
	'Parent',FigureHandle, ...
	'Units','pixels', ...
	'Position',INPUT_TABLE_POSITION, ...
	'CellEditCallback',@SRIMRangeDist.Callback.InputTableCellEdit, ...
	'ColumnName',INPUT_TABLE_COLUMN_NAME, ...
	'ColumnEditable',[true,true], ...
	'ColumnFormat',{'numeric','numeric'}, ...
	'ColumnWidth',{x,x}, ...
	'Data',nan(7,2), ...
	'FontSize',INPUT_TABLE_FONT_SIZE, ...
	'Tag','InputTable', ...
	'TooltipString',['Input the subfolder number and the corresponding ', ...
		'implantation fluence here with positive integers.']);

% Buttons
PushButtonHandle=zeros(1,2);
for i=1:2
	PushButtonHandle(i)=uicontrol( ...
		'Parent',FigureHandle, ...
		'Units','pixels', ...
		'Position',PUSH_BUTTON_POSITION{i}, ...
		'Style','pushbutton', ...
		'String',PUSH_BUTTON_STRING{i}, ...
		'BackgroundColor',PUSH_BUTTON_BACKGROUND_COLOR, ...
		'FontSize',PUSH_BUTTON_FONT_SIZE(i), ...
		'HorizontalAlignment','center');
end
set(PushButtonHandle(1), ...
	'Callback',@SRIMRangeDist.Callback.PushButton1);
set(PushButtonHandle(2), ...
	'Callback',@SRIMRangeDist.Callback.PushButton2);

%% Plot Areas
AxesHandle=axes( ...
	'Parent',FigureHandle, ...
	'Units','pixels', ...
	'Position',AXES_POSITION, ...
	'Box','on', ...
	'XMinorTick','on', ...
	'YMinorTick','on', ...
	'LineWidth',AXES_LINE_WIDTH, ...
	'FontSize',AXES_FONT_SIZE, ...
	'Color',AXES_BACKGROUND_COLOR, ...
	'XColor',AXES_COLOR, ...
	'YColor',AXES_COLOR, ...
	'Tag','Axes');
hold(AxesHandle,'all');
xlabel(X_LABEL_STRING, ...
	'FontSize',AXES_LABEL_FONT_SIZE, ...
	'Color',AXES_LABEL_COLOR);
ylabel(Y_LABEL_STRING, ...
	'FontSize',AXES_LABEL_FONT_SIZE, ...
	'Color',AXES_LABEL_COLOR);

%% Finishing
movegui(FigureHandle,'center');
FigureHandle.Visible='on';

end